LearnEase/src/LearnEase.Presentation/Controllers/AdminPageController.cs
using LearnEase.Core.Models;
using LearnEase.Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace LearnEase.Presentation.Controllers;

[Authorize(Roles = "Admin")]
public class AdminPageController : Controller
{
    private readonly IAdminPageService adminPageService;

    public AdminPageController(IAdminPageService adminPageService)
    {
        this.adminPageService = adminPageService;
    }

    [Authorize(Roles = "Admin")]
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    [Route("[controller]/[action]/{userId}", Name = "ToggleMute")]
    public async Task<IActionResult> ToggleMuteUser(string userId) {
        try {
            await adminPageService.ToggleMuteUser(userId);
        }
        catch (Exception ex) {
            BadRequest(ex.Message);
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    [Route("[controller]/[action]/{userId}", Name = "TogglePromoteToAdmin")]
    public async Task<IActionResult> TogglePromoteToAdmin(string userId) {
        try {
            await adminPageService.TogglePromoteUserToAdmin(userId);
        }
        catch (Exception ex) {
            BadRequest(ex.Message);
        }

        return RedirectToAction("Index");
    }


    [HttpPost]
    [Route("[controller]/[action]/{userId}", Name = "TogglePromoteToAuthor")]
    public async Task<IActionResult> TogglePromoteToAuthor(string userId) {
        try {
            await adminPageService.TogglePromoteUserToAuthor(userId);
        }
        catch (Exception ex) {
            BadRequest(ex.Message);
        }

        return RedirectToAction("Index");
    }

    [HttpPost]
    [Route("[controller]/[action]/{userId}", Name = "ToggleBanUser")]
    public async Task<IActionResult> ToggleBanUser(string userId) {
        try {
            await adminPageService.ToggleBanUser(userId);
        }
        catch (Exception ex) {
            BadRequest(ex.Message);
        }

        return RedirectToAction("Index");
    }
}

LearnEase/src/LearnEase.Presentation/Controllers/CourseController.cs
using FluentValidation;

using LearnEase.Core.Models;
using LearnEase.Core.Services;
using LearnEase.Presentation.Utilities.Extensions;
using LearnEase.Presentation.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace LearnEase.Presentation.Controllers;

[Route("[controller]")]
public class CourseController : Controller
{
    private readonly ICourseService courseService;

    private readonly IFeedbackService feedbackService;

    private readonly IValidator<Course> validator;

    private readonly UserManager<User> userManager;


    public CourseController(ICourseService courseService, IValidator<Course> validator, 
    IFeedbackService feedbackService, UserManager<User> userManager)
    {
        this.courseService = courseService;
        this.validator = validator;
        this.feedbackService = feedbackService;
        this.userManager = userManager;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var courses = await this.courseService.GetAllCoursesAsync();
        return View(courses);
    }


    [Authorize(Roles="Author, Admin")]
    [HttpGet("[action]", Name = "CourseCreateView")]
    public IActionResult Create() {
        return base.View("CourseCreateMenu");
    }
    

    [Authorize(Roles="Author, Admin")]
    [HttpPost(Name = "CourseCreateApi")]
    public async Task<IActionResult> Create([FromForm] Course newCourse, IFormFile? logo) {
        try {
            var validationResult = await validator.ValidateAsync(newCourse);

            var errorHandlerResult = this.HandleValidationErrors(
                validationResult, 
                returnLogic: () => base.View("CourseCreateMenu"),
                pageKey: "CourseCreatePage"
            );
            
            if (errorHandlerResult != null)
                return errorHandlerResult;
                

            await this.courseService.CreateCourseAsync(newCourse);
            await this.courseService.SetCourseLogo(newCourse, logo);
            
            return base.RedirectToAction(actionName: "Index");
        }
        catch (Exception ex) {
            return BadRequest(ex.Message);
        }
    }
    

    [Authorize(Roles="Admin, Author")]
    [HttpDelete("{courseId:int}")]
    public async Task<IActionResult> Delete(int courseId) {
        try
        {
            var course = await courseService.GetCourseByIdAsync(courseId);

            if (course == null)
                return NotFound();

            var user = await userManager.GetUserAsync(User);
            var isAdmin = await userManager.IsInRoleAsync(user, "Admin");

            if (!isAdmin && course.UserId != user?.Id)
                return Forbid();


            await this.feedbackService.DeleteFeedbacksByCourseId(courseId);
            await this.courseService.DeleteCourseLogo(courseId);
            await this.courseService.DeleteCourseByIdAsync(courseId);

            return Ok();
        }
        catch(Exception ex)
        {
            return BadRequest(ex.Message);
        }
    }

    [HttpGet("[action]/{id}")]
    public async Task<IActionResult> Logo(int id) {
        var courses = await courseService.GetAllCoursesAsync();
        var course = courses.FirstOrDefault(c => c.Id == id);

        if (course is null)
            return BadRequest();

        if (course.CourseLogoPath is null)
            return Ok();

        var fileStream = System.IO.File.Open(course.CourseLogoPath, FileMode.Open);
        return base.File(fileStream, "image/jpeg");
    }


    [Authorize(Roles="User, Author, Admin")]
    [HttpGet("[action]", Name = "GetCourseDetails")]
    public async Task<IActionResult> Details(int id) {
        try {
            var course = await courseService.GetCourseByIdAsync(id);

            var viewModel = new CourseDetailsViewModel
            {
                Course = course,
                Lessons = course.Lessons,
                Feedbacks = course.Feedbacks
            };

            return View("CoursePage", viewModel);
        }
        catch (Exception ex) {
            return BadRequest(ex.Message);
        }
    }
}

LearnEase/src/LearnEase.Presentation/Controllers/IdentityController.cs
using FluentValidation;

using LearnEase.Core.Dtos;
using LearnEase.Core.Services;
using LearnEase.Presentation.Utilities.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LearnEase.Presentation.Controllers;

public class IdentityController : Controller
{
    private readonly IValidator<LoginDto> loginValidator;

    private readonly IValidator<RegistrationDto> registrationValidator;

    private readonly IIdentityService identityService; 


    public IdentityController(IIdentityService identityService, IValidator<LoginDto> loginValidator, 
    IValidator<RegistrationDto> registrationValidator)
    {
        this.identityService = identityService;
        this.loginValidator = loginValidator;
        this.registrationValidator = registrationValidator;
    }


    [Route("/[controller]/[action]", Name = "LoginView")]
    public IActionResult Login(string? ReturnUrl)
    {
        this.RestoreValidationErrors("LoginPage");
        ViewBag.ReturnUrl = ReturnUrl;

        return base.View();
    }


    [HttpPost]
    [Route("/api/[controller]/[action]", Name = "LoginEndpoint")]
    public async Task<IActionResult> Login([FromForm] LoginDto loginDto)
    {
        try 
        {
            var validationResult = await loginValidator.ValidateAsync(loginDto);

            var errorHandlerResult = this.HandleValidationErrors(
                validationResult, 
                returnLogic: () => base.RedirectToRoute("LoginView", new { loginDto.ReturnUrl }),
                pageKey: "LoginPage"
            );
            
            if (errorHandlerResult != null)
                return errorHandlerResult;

            await identityService.SignInAsync(loginDto);

            if (string.IsNullOrWhiteSpace(loginDto.ReturnUrl) == false)
                return base.Redirect(loginDto.ReturnUrl);

            return base.RedirectToAction(controllerName: "Home", actionName: "Index");
        }
        catch (Exception ex)
        {
            base.TempData["AuthenticationError"] = ex.Message;

            return base.RedirectToRoute("LoginView", new
            {
                loginDto.ReturnUrl
            });
        }
    }

    [Route("/[controller]/[action]", Name = "RegistrationView")]
    public IActionResult Registration()
    {
        return base.View();
    }

    [HttpPost]
    [Route("/api/[controller]/[action]", Name = "RegistrationEndpoint")]
    public async Task<IActionResult> Registration([FromForm] RegistrationDto registrationDto)
    {
        try
        {
            var validationResult = await registrationValidator.ValidateAsync(registrationDto);
            
            var errorHandlerResult = this.HandleValidationErrors(
                validationResult, 
                returnLogic: () => base.View(),
                pageKey: "RegisterPage"
            );

            if (errorHandlerResult != null)
                return errorHandlerResult;

            await identityService.RegisterAsync(registrationDto);
            await identityService.SetDefaultAvatarAsync(registrationDto.Login);

            return base.RedirectToRoute("LoginView");
        }
        catch (Exception ex)
        {
            this.ModelState.AddModelError("Password", ex.Message);
            return base.View();
        }
    }

    [Authorize]
    [HttpGet("[controller]/[action]/{userId}")]
    public async Task<IActionResult> Avatar(string userId) {
        
        var user = await identityService.FindUserById(userId);

        if (user is null)
            return BadRequest();

        if (user.AvatarPath is null)
            return Ok();

        var fileStream = System.IO.File.Open(user.AvatarPath, FileMode.Open);
        return base.File(fileStream, "image/jpeg");
    }

    [Authorize]
    [HttpPost]
    [Route("[controller]/[action]/{userId}", Name = "SetAvatar")]
    public async Task<IActionResult> SetAvatar(string userId, IFormFile? avatar) {
        try {
            await this.identityService.SetAvatarAsync(userId, avatar);
            return RedirectToAction(controllerName: "UserProfile", actionName: "Index");
        }
        catch (Exception ex) {
            return BadRequest(ex.Message);
        }
    }


    [HttpGet]
    [Route("/api/[controller]/[action]")]
    public async Task<IActionResult> Logout(string? ReturnUrl)
    {
        await identityService.SignOutAsync();

        return base.RedirectToRoute(routeName: "LoginView", routeValues: new
        {
            ReturnUrl
        });
    }
}

LearnEase/src/LearnEase.Presentation/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager;
@inject SignInManager<User> SignInManager;

@{
    var userRoles = new List<string>();
    var authenticatedUser = await UserManager.GetUserAsync(User);
    var IsAdmin = false;
    var isSignedIn = authenticatedUser is not null;

    if (isSignedIn) {
        userRoles = (await UserManager.GetRolesAsync(authenticatedUser)).ToList();
        IsAdmin = userRoles.Contains("Admin");
    }
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LearnEase.Presentation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/LearnEase.Presentation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">LearnEase</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>

                        @if(isSignedIn == false) {
                            <li class="nav-item">
                                <a class="nav-link text-dark text-right" asp-route="LoginView">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark text-right" asp-route="RegistrationView">Registration</a>
                            </li>
                        }
                        else {
                            @if (IsAdmin) {
                                <li class="nav-item ml-auto">
                                    <a class="nav-link text-dark" asp-controller="AdminPage" asp-action="Index">AdminPage</a>
                                </li>
                            }

                            <li class="nav-item ml-auto">
                                <a class="nav-link text-dark" asp-controller="UserProfile" asp-action="Index">User</a>
                            </li>

                            <li class="nav-item ml-auto">
                                <a class="nav-link text-dark" asp-controller="Identity" asp-action="Logout">Logout</a>
                            </li>
                        }
                        
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - LearnEase.Presentation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>